# Generated by Django 3.2.2 on 2021-05-10 21:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('data_inicio', models.DateField(verbose_name='data de início')),
                ('data_termino', models.DateField(verbose_name='data de término')),
                ('investimento_diario', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='investimento diário')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anuncios', to='anuncios.cliente')),
            ],
            options={
                'verbose_name': 'anúncio',
                'db_table': 'anuncio',
                'ordering': ['-data_inicio'],
            },
        ),
    ]
