# Generated by Django 3.2.2 on 2021-05-17 00:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anuncio',
            options={'ordering': ['-data_inicio', '-data_termino'], 'verbose_name': 'anúncio', 'verbose_name_plural': 'anúncios'},
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nome']},
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='investimento_diario',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='investimento diário'),
        ),
    ]
